#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { repoRoot, slash, hasSymlinkComponent, atomicWrite } = require("./lib/common.cjs");
const { collect, resolveWikiLink, kind } = require("./lib/wiki-graph.cjs");

function connections(graph) {
  const counts = { index: 0, topic: 0, journal: 0, plan: 0 };
  for (const node of graph.nodes) counts[node.type]++;
  const lines = [
    "# Wiki connections", "", "Generated by `node scripts/wiki/build-graph.cjs`. Do not edit by hand.", "",
    `- Indexes: ${counts.index}`, `- Topics: ${counts.topic}`, `- Journals: ${counts.journal}`, `- Plans: ${counts.plan}`, `- Relationships: ${graph.edges.length}`, "", "## Relationships", "",
  ];
  const markdownLabel = (value) => String(value).replace(/\r?\n/g, " ").replace(/\\/g, "\\\\").replaceAll("[", "\\[").replaceAll("]", "\\]");
  const markdownHref = (value) => `../${String(value).split("/").map(encodeURIComponent).join("/")}`;
  for (const edge of graph.edges) lines.push(`- [${markdownLabel(edge.source)}](${markdownHref(edge.source)}) → [${markdownLabel(edge.target)}](${markdownHref(edge.target)}) (${edge.type})`);
  if (!graph.edges.length) lines.push("- None yet.");
  return lines.join("\n") + "\n";
}

function main() {
  const check = process.argv.includes("--check");
  const repoArg = process.argv.indexOf("--repo");
  const root = repoRoot(repoArg >= 0 ? process.argv[repoArg + 1] : process.cwd());
  try {
    const graph = collect(root);
    const graphBytes = JSON.stringify(graph, null, 2) + "\n";
    const connectionsBytes = connections(graph);
    const targets = [[path.join(root, "scripts/wiki/graph/data/graph.json"), graphBytes], [path.join(root, "wiki/connections.md"), connectionsBytes]];
    const unsafe = targets.filter(([file]) => hasSymlinkComponent(root, file)).map(([file]) => slash(path.relative(root, file)));
    if (unsafe.length) throw new Error(`generated output path contains a symbolic link: ${unsafe.join(", ")}`);
    if (check) {
      const stale = targets.filter(([file, bytes]) => !fs.existsSync(file) || fs.readFileSync(file, "utf8") !== bytes).map(([file]) => slash(path.relative(root, file)));
      if (stale.length) throw new Error(`generated graph is stale: ${stale.join(", ")}`);
    } else {
      for (const [file, bytes] of targets) atomicWrite(file, bytes);
    }
    console.log(`PASS wiki graph: ${graph.nodes.length} nodes, ${graph.edges.length} edges${check ? " (fresh)" : ""}`);
    return 0;
  } catch (error) { console.error(`FAIL ${error.message}`); return 2; }
}

if (require.main === module) process.exit(main());
module.exports = { collect, connections, resolveWikiLink, kind };
