import { compileApplicability, resolutionStates, triggerStates } from './compile-applicability.mjs';
import { buildLaneCoverage } from './coverage.mjs';
import { canonicalize, digest } from './digest.mjs';
import { projectionProvenance } from './provenance.mjs';

export const marker = 'GENERATED by @verndale/accessibility-standards; DO NOT EDIT';

function json(payload, provenance) {
  return `${JSON.stringify(canonicalize({ _generated: marker, _provenance: provenance, ...payload }), null, 2)}\n`;
}

function markdownDocument(title, content, provenance) {
  return `<!-- ${marker} -->\n<!-- package: ${provenance.package}; profile: ${provenance.profile}@${provenance.profile_version}; schema: ${provenance.schema_version}; source-digest: ${provenance.source_digest}; profile-digest: ${provenance.profile_digest} -->\n# ${title}\n\n${content}\n`;
}

function markdown(title, records, body, provenance) {
  return markdownDocument(title, records.map(body).join('\n\n'), provenance);
}

function markdownText(value) {
  return String(value)
    .replaceAll('\\', '\\\\')
    .replace(/([\[\]`*_{}])/g, '\\$1')
    .replace(/\r?\n/g, ' ');
}

function markdownUrl(value) {
  return `<${String(value).replace(/[<>\s]/g, (character) => encodeURIComponent(character))}>`;
}

function tableCell(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('\\', '&#92;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replace(/\r\n?|\n/g, '<br>')
    .replaceAll('|', '\\|');
}

function embeddedJson(value) {
  return JSON.stringify(canonicalize(value)).replaceAll('`', '\\u0060');
}

function standardsReferences(refs) {
  return refs.map((ref) => `- [${markdownText(`${ref.authority} ${ref.identifier}`)}](${markdownUrl(ref.url)})${ref.level ? ` (Level ${ref.level})` : ''} — ${ref.normative ? 'normative' : 'informative'}`).join('\n');
}

function semanticSection(item) {
  return `## ${item.id}\n\n${item.requirement}\n\nStandards:\n${standardsReferences(item.standards_refs)}\n\nProof: ${item.proof.join(', ')}.`;
}

function patternSection(item) {
  return `## ${item.id}\n\nStandards:\n${standardsReferences(item.standards_refs)}\n\nRequires: ${item.requires.join(', ')}.\n\nActivation: \`${embeddedJson(item.activation)}\`\n\nScope: ${item.scope}.\n\nBehavior:\n${item.behavior.map((line) => `- ${line}`).join('\n')}\n\nProduct decisions: ${item.product_decisions.join(', ')}.\n\nFunctional Spec bindings: ${item.functional_spec_bindings.join(', ')}.\n\nImplementation outcomes: ${item.implementation_outcomes.join(', ')}.\n\nEvidence: ${item.evidence_routes.join(', ')}.`;
}

function requirementSection(item) {
  return `## ${item.id}\n\n${item.requirement}`;
}

function applicabilitySection(item) {
  return `## ${item.id}\n\nWhen: \`${embeddedJson(item.when)}\`\n\nOutcomes: ${item.outcomes.join(', ')}.\n\nEvidence: ${item.evidence.join(', ')}.`;
}

function evidenceSection(data) {
  const routes = Object.entries(data.evidence.proof_kinds).sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0);
  return `## Evidence routing\n\n${data.evidence.rule}\n\n${routes.map(([id, route]) => `- ${id}: ${route.purpose}; capability: ${route.required_capability}`).join('\n')}`;
}

function wcagCoverageSection(coverage) {
  const counts = Object.fromEntries(['covered', 'partial', 'gap'].map((status) => [status, coverage.criteria.filter((criterion) => criterion.status === status).length]));
  const rows = coverage.criteria.map((criterion) => {
    const semantics = criterion.semantic_ids.length ? criterion.semantic_ids.join(', ') : '—';
    const note = criterion.note ?? '—';
    return `| ${[criterion.id, criterion.title, criterion.level, criterion.status, semantics, note].map(tableCell).join(' | ')} |`;
  });
  const deferred = coverage.deferred_patterns.map(({ id, reason }) => `- ${markdownText(id)}: ${markdownText(reason)}`).join('\n');
  return `## WCAG 2.2 Level A/AA coverage\n\nCoverage is criterion-level traceability, not a conformance claim: ${counts.covered} covered, ${counts.partial} partial, and ${counts.gap} gaps.\n\n| Criterion | Title | Level | Status | Semantic IDs | Note |\n| --- | --- | --- | --- | --- | --- |\n${rows.join('\n')}\n\n### Deferred APG patterns\n\n${deferred}`;
}

export function buildArtifacts(data, profile) {
  const provenance = projectionProvenance(data, profile);
  const foundations = [...data.foundations].sort(byId);
  const semantics = [...data.semantics].sort(byId);
  const patterns = [...data.patterns].sort(byId);
  const policies = [...data.policies].sort(byId);
  const compiled = compileApplicability(data.matrix, data.facts);
  const bindingDigest = digest(data.uiDesignBrainBindings);
  const uiPatternIds = data.uiDesignBrainBindings.bindings.map(({ ui_pattern_id }) => ui_pattern_id);
  const ids = [...foundations, ...semantics, ...patterns, ...policies, ...data.matrix.rows].map(({ id }) => id).sort();
  const laneCoverage = buildLaneCoverage(data);
  const artifacts = new Map();
  artifacts.set('semanticsJson', json({ schema_version: data.contract.schema_version, foundations, semantics, policies }, provenance));
  artifacts.set('patternContracts', json({ schema_version: data.contract.schema_version, patterns }, provenance));
  artifacts.set('uiDesignBrainBindings', json({ schema_version: data.contract.schema_version, binding_schema_version: data.uiDesignBrainBindings.version, source: data.uiDesignBrainBindings.source, binding_digest: bindingDigest, bindings: data.uiDesignBrainBindings.bindings }, provenance));
  artifacts.set('coverageManifest', json({
    schema_version: data.contract.schema_version,
    projected_ids: ids,
    ui_pattern_ids: uiPatternIds,
    ui_design_brain: { ...data.uiDesignBrainBindings.source, binding_digest: bindingDigest },
    lane_coverage: laneCoverage,
    wcag_2_2: data.wcagCoverage
  }, provenance));
  if (profile === 'conductor') {
    const authoritySections = [
      ...foundations.map(requirementSection),
      ...semantics.map(semanticSection),
      ...policies.map(requirementSection),
      wcagCoverageSection(data.wcagCoverage),
    ].join('\n\n');
    const qualitySections = [
      ...patterns.map(patternSection),
      ...compiled.map(applicabilitySection),
      evidenceSection(data),
    ].join('\n\n');
    artifacts.set('semanticsMarkdown', markdownDocument('Accessibility foundations, semantics, and policies', authoritySections, provenance));
    artifacts.set('qualityMarkdown', markdownDocument('Accessibility quality contract', qualitySections, provenance));
    artifacts.set('applicabilityMatrix', json({ schema_version: data.contract.schema_version, trigger_states: triggerStates, resolution_states: resolutionStates, facts: data.facts.facts, rows: compiled, evidence: data.evidence }, provenance));
    for (const pattern of patterns) artifacts.set(`pattern:${pattern.id}`, json({ schema_version: data.contract.schema_version, pattern }, provenance));
  } else if (profile === 'ai-orchestration') {
    for (const semantic of semantics) artifacts.set(`semantic:${semantic.id}`, markdown(semantic.id, [semantic], semanticSection, provenance));
    for (const pattern of patterns) artifacts.set(`pattern:${pattern.id}`, markdown(pattern.id, [pattern], patternSection, provenance));
    const implementationSections = [
      ...foundations.map(requirementSection),
      ...semantics.map(semanticSection),
      ...patterns.map(patternSection),
      ...compiled.map(applicabilitySection),
      ...policies.map(requirementSection),
      wcagCoverageSection(data.wcagCoverage),
      evidenceSection(data),
    ].join('\n\n');
    artifacts.set('implementation', markdownDocument('Accessibility implementation contract', implementationSections, provenance));
    artifacts.set('testing', markdownDocument('Accessibility testing contract', Object.entries(laneCoverage).map(([lane, laneIds]) => `## ${lane}\n\n${laneIds.map((id) => `- ${id}`).join('\n')}`).join('\n\n'), provenance));
    artifacts.set('review', markdownDocument('Accessibility review contract', `Review in this order: source compatibility, foundations, semantic dependencies, pattern behavior, applicability outcomes, implementation outcomes, test lanes, human evidence.\n\n${ids.map((id) => `- ${id}`).join('\n')}`, provenance));
  } else throw new Error(`Unknown profile: ${profile}`);
  return artifacts;
}

export function defaultPath(key, profile) {
  const fixed = profile === 'conductor' ? {
    semanticsMarkdown: 'a11y-semantics.md', qualityMarkdown: 'accessibility-quality.md', semanticsJson: 'semantics.json', patternContracts: 'pattern-contracts.json', applicabilityMatrix: 'applicability-matrix.json', uiDesignBrainBindings: 'ui-design-brain-bindings.json', coverageManifest: 'coverage-manifest.json'
  } : {
    semanticsJson: 'semantics.json', patternContracts: 'pattern-contracts.json', uiDesignBrainBindings: 'ui-design-brain-bindings.json', coverageManifest: 'coverage-manifest.json', implementation: 'implementation/accessibility.md', testing: 'testing/accessibility.md', review: 'review/accessibility.md'
  };
  if (fixed[key]) return fixed[key];
  if (key.startsWith('pattern:')) return `patterns/${key.slice(8).replace('pattern.', '')}.${profile === 'conductor' ? 'json' : 'md'}`;
  if (key.startsWith('semantic:')) return `semantics/${key.slice(9).replace('semantics.', '')}.md`;
  throw new Error(`No output path for ${key}`);
}

export function artifactDigestMap(artifacts) {
  return Object.fromEntries([...artifacts].sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => [key, digest(value)]));
}

const byId = (a, b) => a.id.localeCompare(b.id);
