import { compileApplicability, resolutionStates, triggerStates } from './compile-applicability.mjs';
import { digest } from './digest.mjs';

export const marker = 'GENERATED by @verndale/accessibility-standards; DO NOT EDIT';

function json(payload) {
  return `${JSON.stringify({ _generated: marker, ...payload }, null, 2)}\n`;
}

function markdown(title, records, body) {
  return `<!-- ${marker} -->\n# ${title}\n\n${records.map(body).join('\n\n')}\n`;
}

function semanticSection(item) {
  return `## ${item.id}\n\n${item.requirement}\n\nProof: ${item.proof.join(', ')}.`;
}

function patternSection(item) {
  return `## ${item.id}\n\nRequires: ${item.requires.join(', ')}.\n\nBehavior:\n${item.behavior.map((line) => `- ${line}`).join('\n')}\n\nEvidence: ${item.evidence_routes.join(', ')}.`;
}

export function buildArtifacts(data, profile) {
  const semantics = [...data.semantics].sort(byId);
  const patterns = [...data.patterns].sort(byId);
  const compiled = compileApplicability(data.matrix, data.facts);
  const ids = [...semantics.map(({ id }) => id), ...patterns.map(({ id }) => id), ...data.matrix.rows.map(({ id }) => id)].sort();
  const laneCoverage = Object.fromEntries(Object.keys(data.evidence.proof_kinds).sort().map((lane) => [lane, idsForLane(data, lane)]));
  const artifacts = new Map();
  artifacts.set('semanticsJson', json({ schema_version: 1, semantics }));
  artifacts.set('patternContracts', json({ schema_version: 1, patterns }));
  artifacts.set('coverageManifest', json({ schema_version: 1, projected_ids: ids, lane_coverage: laneCoverage }));
  if (profile === 'conductor') {
    artifacts.set('semanticsMarkdown', markdown('Accessibility semantics', semantics, semanticSection));
    artifacts.set('qualityMarkdown', markdown('Accessibility quality contract', patterns, patternSection));
    artifacts.set('applicabilityMatrix', json({ schema_version: 1, trigger_states: triggerStates, resolution_states: resolutionStates, facts: data.facts.facts, rows: compiled }));
    for (const pattern of patterns) artifacts.set(`pattern:${pattern.id}`, json({ schema_version: 1, pattern }));
  } else if (profile === 'ai-orchestration') {
    for (const semantic of semantics) artifacts.set(`semantic:${semantic.id}`, markdown(semantic.id, [semantic], semanticSection));
    for (const pattern of patterns) artifacts.set(`pattern:${pattern.id}`, markdown(pattern.id, [pattern], patternSection));
    artifacts.set('implementation', markdown('Accessibility implementation contract', [...semantics, ...patterns], (item) => item.kind === 'semantic' ? semanticSection(item) : patternSection(item)));
    artifacts.set('testing', `<!-- ${marker} -->\n# Accessibility testing contract\n\n${Object.entries(laneCoverage).map(([lane, laneIds]) => `## ${lane}\n\n${laneIds.map((id) => `- ${id}`).join('\n')}`).join('\n\n')}\n`);
    artifacts.set('review', `<!-- ${marker} -->\n# Accessibility review contract\n\nReview in this order: source compatibility, semantic dependencies, pattern behavior, implementation outcomes, test lanes, human evidence.\n\n${ids.map((id) => `- ${id}`).join('\n')}\n`);
  } else throw new Error(`Unknown profile: ${profile}`);
  return artifacts;
}

export function defaultPath(key, profile) {
  const fixed = profile === 'conductor' ? {
    semanticsMarkdown: 'a11y-semantics.md', qualityMarkdown: 'accessibility-quality.md', semanticsJson: 'semantics.json', patternContracts: 'pattern-contracts.json', applicabilityMatrix: 'applicability-matrix.json', coverageManifest: 'coverage-manifest.json'
  } : {
    semanticsJson: 'semantics.json', patternContracts: 'pattern-contracts.json', coverageManifest: 'coverage-manifest.json', implementation: 'implementation/accessibility.md', testing: 'testing/accessibility.md', review: 'review/accessibility.md'
  };
  if (fixed[key]) return fixed[key];
  if (key.startsWith('pattern:')) return `patterns/${key.slice(8).replace('pattern.', '')}.${profile === 'conductor' ? 'json' : 'md'}`;
  if (key.startsWith('semantic:')) return `semantics/${key.slice(9).replace('semantics.', '')}.md`;
  throw new Error(`No output path for ${key}`);
}

export function artifactDigestMap(artifacts) {
  return Object.fromEntries([...artifacts].sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => [key, digest(value)]));
}

function idsForLane(data, lane) {
  return [...new Set([
    ...data.semantics.filter((item) => item.proof.includes(lane)).map(({ id }) => id),
    ...data.patterns.filter((item) => item.evidence_routes.includes(lane)).map(({ id }) => id),
    ...data.matrix.rows.filter((item) => item.evidence.includes(lane)).flatMap((item) => item.outcomes)
  ])].sort();
}

const byId = (a, b) => a.id.localeCompare(b.id);
